run:
  timeout: 5m
  go: '1.21'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/cupbot/cupbot
  
  golint:
    min-confidence: 0.8
  
  misspell:
    locale: US
  
  unparam:
    check-exported: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  disable:
    - gochecknoglobals  # Allow globals for configuration
    - gocognit         # Duplicate of gocyclo
    - godot            # Allow comments without periods
    - godox            # Allow TODO comments
    - goerr113         # Allow dynamic errors
    - nestif           # Allow nested if statements
    - nlreturn         # Don't require newlines
    - testpackage      # Allow tests in same package
    - wsl              # Don't enforce whitespace style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec      # Security issues less critical in tests
        - funlen     # Test functions can be long
        - dupl       # Duplicate code acceptable in tests
        - gomnd      # Magic numbers acceptable in tests
    
    - path: main\.go
      linters:
        - gochecknoinits  # Allow init in main
    
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

severity:
  default-severity: error
  case-sensitive: false