run:
  timeout: 10m  # Increased timeout
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
  
  govet:
    shadow:
      strict: false
  
  gocyclo:
    min-complexity: 15
  
  goimports:
    local-prefixes: github.com/cupbot/cupbot
  
  misspell:
    locale: US

  gosec:
    excludes:
      - G404  # Use of weak random number generator
  
  funlen:
    lines: 100
    statements: 50

linters:
  enable:
    # Essential linters only
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Basic code quality
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    
    # Security
    - gosec
    
    # Performance
    - prealloc

issues:
  exclude-dirs:
    - vendor
    - .git
    - test-results
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - funlen
        - gocyclo
    
    - text: "weak cryptographic primitive"
      linters:
        - gosec
        
    - text: "undefined: yaml"
      linters:
        - typecheck
        
    - linters:
        - typecheck
      text: "could not import.*windows"
      
    - linters:
        - typecheck  
      text: "build constraints exclude all Go files"
  
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false