name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Update dependencies
      run: |
        go get -u ./...
        go mod tidy
        
    - name: Run tests
      run: go test -v ./internal/...
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'deps: update Go dependencies'
        title: '🔄 Automated dependency updates'
        body: |
          ## 🔄 Automated Dependency Updates
          
          This PR contains automated updates to Go dependencies.
          
          ### Changes
          - Updated Go modules to latest compatible versions
          - Ran `go mod tidy` to clean up dependencies
          
          ### Testing
          - ✅ All tests pass with updated dependencies
          - ✅ No breaking changes detected
          
          ### Review Checklist
          - [ ] Review updated dependency versions
          - [ ] Check for any security advisories
          - [ ] Verify tests pass in CI
          - [ ] Confirm no breaking changes
          
          **Auto-generated by GitHub Actions**
        branch: deps/auto-update
        labels: |
          dependencies
          automated
        delete-branch: true